jwt:
  secretKey: ZXlKcGRpSTZJbXh6YzJsa0lpd2libUZ0WlNJNklqVXpNVEF3TXpNMU5USXhOaUlzSW1WNGNDSTZNVFl4TXpjeU5qWXdNRFV4TENKcGMzTWlPaUpvZEhSd2N6b3ZMM0J5YjNKMExYTnZZMnRsY3k1amIyMGlMQ0p6ZFdJaU9pSm9kSFJ3Y3pvdkwzQnliM0owTFhOdlltRjBhVzl1SWl3aWMyTnZjaUk2SW5WdFlXbHNZV2RsYm1GdFpTQjkuZVVmR2dBcUtaX2ZRVGhSeXFES3ZNdDZqM3ZHM1ZVM0JZdElFQU1NdQ==




server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**
          filters:
            - name: AuthenticationFilter

        - id: trip-service
          uri: lb://trip-service
          predicates:
            - Path=/api/v1/trip/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: companion-service
          uri: lb://companion-service
          predicates:
            - Path=/api/v2/companion/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter


        - id: matching-service
          uri: lb://matching-service
          predicates:
            - Path=/api/v3/matching/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter


        - id: Bot-service
          uri: lb://Bot-service
          predicates:
            - Path=/api/v4/bot/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
