jwt:
  secretKey: rfufjjhffdstigjkhivnbfkgghiuregfgfgkfnfbgfgrfhreifegtegjgjfjvcvnkffdghgregrelgjore

server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**
          filters:
            - name: AuthenticationFilter

        - id: trip-service
          uri: lb://trip-service
          predicates:
            - Path=/api/v1/trip/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
